# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VntS9UUZeJh5A8qiwU0/egA6J5PoifrxuBKPfxEg/Oog7U+GUav1H6SXCOrcMZ0BUYfLxOYj71OPU1L5UDKPaRdkbsUSvQDcqW8Rh3lzE9UT4u/iQuWWYfG0M3zZyH6gNpQkIWgaRAshKPMzi6hSTFEWwvJED8GZPvmZwgm3UYktENl+n/GVJYXLquMoCdL/Z2z0tFvJ2iucNnVaceM4DZEq4LJy7IcVrW0khk/fzjQZkrekbtQ5pHgxUKOBdmM2U1WftdzjEBlukkDa5yfRsTzuIK/6vpyhspvH3okDUFIhkjH4WowqWTqKDzJFbCurjb9hZLaTOxI6362XBh3K3DT4wW7YQ7pAGYyQQK5FneN4YAq8uzoka5gXD3vM7hFIDc383sprEHNp6T4+sYl6H+pCqRP2HmdCGBlm+FGsdSIkaOYGJW809n7fOnfV5mz3pkhrsJiI1RNPXlgg+90o1ydVR1K3ZjO0keVnsJa+V/q/4CBqJaD757IMjji3z6/Q0F14CgZdWmrPU6oMo8gxA+s7gp2ys5tYqrvfaKfgS/aIdfKRbfoXDjMbK7p8fAgaKI10cqU88efMx108OOOpPdEwCzVpj4XoCiiUdGymTAMjErSICis/RZnajX8+9QCPBR8r99YBkc1QXf7hPrrfwmJJzUvTiBGTGXQioDha8gE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
